var imageUrl = [];
har.log.entries.forEach(function (entry) {
  if (entry.response.content.mimeType.indexOf("image/") !== 0) return;
  imageUrl.push(entry.request.url);
});
console.log(imageUrl.join("\n"));

/*

https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/photos-videos/photos_videos_startframe__dnwwa2e1qys2_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/entertainment/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/apps/apps_startframe__fgskz7opptiu_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/intro/intro_spin_endframe__dy927flmi3au_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/intro/logo__4zgkuyebgtem_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/inputs_startframe__ggmu2xwjf662_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/digital_canvas_startframe__dn0uk8v419km_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/spatial_computing_startframe__rtxdvqb0m1ei_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/hero/hero_startframe__k6x4mt11vf2u_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/quicklook_placeholder__eu3anwy8icae_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/hero/hero_endframe__dz973mndvu82_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/spatial_computing_startframe__rtxdvqb0m1ei_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/digital_canvas_startframe__dn0uk8v419km_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/inputs_startframe__ggmu2xwjf662_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/intro/intro_spin_endframe__dy927flmi3au_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/apps/apps_startframe__fgskz7opptiu_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/entertainment/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/photos-videos/photos_videos_startframe__dnwwa2e1qys2_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/connection/connection_startframe__dk2ju081ayqa_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_top__k3b8lzqd1l2m_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/hero/apple_vision_pro_logo__ux94yix23r6y_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_side__gm4agomrwl2e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_startframe__fvet9b5mg86e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/light_seal__fo87cv0zkcmm_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/hero_startframe__k6x4mt11vf2u_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/scaling_ui__gosi0305um2y_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/spatial_interaction__br11mf88bzxy_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_mt_hood__bowcnbltk57m_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_white_sand__d9yi9qfevrue_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_moon__cddspuen58eq_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/around_you__bfdlxkwczahe_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/spatial_audio_startframe__dl2iakzba36u_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/eye_tracking_off__fx6m2dj3mlqq_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/eye_tracking_on__ln11reqs6mi6_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_off__cfzcmow4c3f6_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_video__b8xghearfs76_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_tracking__dssyfpe9tc66_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_mapping__3hn0pwmp7v6e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_all__dp0a8e4y4u4i_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_chips__s805s5o3gkii_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/ar_logo__bmtaba6ckk76_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/ar_tile__que64jqs2t2e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/developers__bxrd1uafspsi_large.png
https://www.apple.com/ac/globalfooter/8/en_US/assets/ac-footer/breadcrumbs/apple/icon_large.svg
https://www.apple.com/ac/globalfooter/8/en_US/assets/ac-footer/breadcrumbs/separator/icon_large.svg
https://www.apple.com/ac/ac-video-posterframe/4.0/images/ac_video_poster_960x540.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/hero/hero_endframe__dz973mndvu82_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/spatial_computing_startframe__rtxdvqb0m1ei_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/digital_canvas_startframe__dn0uk8v419km_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/inputs_startframe__ggmu2xwjf662_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/foundation/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/intro/logo__4zgkuyebgtem_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/intro/intro_spin_endframe__dy927flmi3au_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/apps/apps_startframe__fgskz7opptiu_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/entertainment/entertainment_startframe__o6s8ikcayjum_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/photos-videos/photos_videos_startframe__dnwwa2e1qys2_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/experiences/connection/connection_startframe__dk2ju081ayqa_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_top__k3b8lzqd1l2m_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_side__gm4agomrwl2e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/glass_startframe__fvet9b5mg86e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/design/light_seal__fo87cv0zkcmm_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/hero_startframe__k6x4mt11vf2u_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/scaling_ui__gosi0305um2y_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/spatial_interaction__br11mf88bzxy_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/eye_tracking_off__fx6m2dj3mlqq_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_off__cfzcmow4c3f6_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_video__b8xghearfs76_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_tracking__dssyfpe9tc66_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_mapping__3hn0pwmp7v6e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0007__b95s4g085uuu_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0006__enypileapsa6_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0004__fq0enfas7sia_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0003__cneophpf8hw2_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0002__fspgzjetnpm6_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/parts_0000__b5n7ez3p2seq_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/displays/startframe__fk6tsxxwncyi_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_mt_hood__bowcnbltk57m_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_white_sand__d9yi9qfevrue_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/environment_moon__cddspuen58eq_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/visionos/around_you__bfdlxkwczahe_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/spatial_audio_startframe__dl2iakzba36u_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/eye_tracking_on__ln11reqs6mi6_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_all__dp0a8e4y4u4i_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/technology/features/sensors_chips__s805s5o3gkii_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/privacy/lock__eqfvj9j7cas2_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/ar_logo__bmtaba6ckk76_large.png
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/ar_tile__que64jqs2t2e_large.jpg
https://www.apple.com/v/apple-vision-pro/c/images/overview/routers/developers__bxrd1uafspsi_large.png 
*/
